runtime: python312
instance_class: F2
entrypoint: gunicorn -b :$PORT app:app --timeout 120

# env_variables are included from secret.yaml

automatic_scaling:
  min_instances: 1
  max_instances: 2
  min_idle_instances: 0
  max_idle_instances: 1
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.6

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

includes:
- secret.yaml